apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
      nodePort: 31936  # fixed NodePort for stability
